name: Update Videos and HTML

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3:00 AM UTC
  workflow_dispatch:     # Allows manual triggering via GitHub UI

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Decode Telegram session file
      run: |
        echo "${{ secrets.TELEGRAM_SESSION_B64 }}" | base64 -d > session_name.session

    - name: Run Telegram download script
      env:
        API_ID: ${{ secrets.TG_API_ID }}
        API_HASH: ${{ secrets.TG_API_HASH }}
      run: python update_videos.py

    - name: Generate HTML
      run: python generate_html.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "🔄 Auto-update videos and HTML" || echo "No changes to commit"
        git push
